/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs. It is checked in here
// so TypeScript has the expected framework types from the first run.
